# Generated by Django 2.0.7 on 2018-07-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0002_auto_20180705_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='date_create',
        ),
        migrations.AddField(
            model_name='comment',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='failure_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
