# Generated by Django 2.0.7 on 2018-07-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0004_auto_20180711_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
