# Generated by Django 2.0.7 on 2018-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0006_useraccept'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccept',
            name='failure',
            field=models.BooleanField(default=False),
        ),
    ]
