# Generated by Django 2.0.7 on 2018-07-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0007_useraccept_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccept',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
