# Generated by Django 2.0.7 on 2018-07-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0009_auto_20180717_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='competence',
        ),
        migrations.AddField(
            model_name='comment',
            name='competence',
            field=models.ManyToManyField(to='smart_contract.Competence'),
        ),
    ]
