# Generated by Django 2.0.7 on 2018-07-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0010_auto_20180717_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccept',
            name='company',
            field=models.CharField(default='OOO Mail.ru', max_length=100),
            preserve_default=False,
        ),
    ]
