# Generated by Django 2.0.7 on 2018-07-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0011_auto_20180717_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccept',
            name='category',
            field=models.IntegerField(choices=[(1, 'Исполнитель'), (2, 'Заказчик'), (3, 'Верификатор')], default=0),
        ),
    ]
