# Generated by Django 2.0.7 on 2018-07-24 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_contract', '0012_useraccept_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccept',
            name='category',
        ),
        migrations.AddField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='customer_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='implementer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='implementer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='implementer_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competence',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
