# Generated by Django 2.0.7 on 2018-07-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0013_auto_20180724_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='files',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], default=0),
        ),
    ]
