# Generated by Django 2.0.7 on 2018-07-26 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_contract', '0015_comment_init_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='employee',
            field=models.ManyToManyField(related_name='employee_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
