# Generated by Django 2.0.7 on 2018-07-27 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_contract', '0016_comment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='another_employee',
            field=models.ManyToManyField(related_name='another_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
