# Generated by Django 2.0.7 on 2018-07-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0017_comment_another_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='another_employee',
            field=models.ManyToManyField(related_name='another_employee', to='smart_contract.UserAccept'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='employee',
            field=models.ManyToManyField(related_name='employee_list', to='smart_contract.UserAccept'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='init_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init_user', to='smart_contract.UserAccept'),
        ),
    ]
