# Generated by Django 2.0.7 on 2018-07-27 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0018_auto_20180727_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='another_employee',
            field=models.ManyToManyField(related_name='another_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='employee',
            field=models.ManyToManyField(related_name='employee_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='init_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
