# Generated by Django 2.0.7 on 2018-08-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0019_auto_20180727_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccept',
            name='position',
            field=models.CharField(default='Team Lead', max_length=100),
            preserve_default=False,
        ),
    ]
