# Generated by Django 2.0.7 on 2018-08-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0020_useraccept_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating_competence',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating_employee',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], default=0),
        ),
    ]
