# Generated by Django 2.0.7 on 2018-08-11 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_contract', '0022_auto_20180811_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='adition_user',
            field=models.ManyToManyField(blank=True, related_name='adition_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
