# Generated by Django 2.1 on 2018-08-30 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0027_auto_20180819_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='another_employee',
            field=models.ManyToManyField(blank=True, related_name='another_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='employee_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
