# Generated by Django 2.1 on 2018-08-30 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0029_disputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputs',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
