# Generated by Django 2.2.5 on 2019-09-30 19:36

from django.db import migrations, models
import smart_contract.models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0032_auto_20190922_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название компании')),
                ('legal_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Юридический адресс')),
                ('TIN', models.BigIntegerField(help_text='10 целых чисел', unique=True, verbose_name='ИНН')),
                ('PSRN', models.BigIntegerField(help_text='13 целых чисел', unique=True, verbose_name='ОГРН')),
                ('KPP', models.BigIntegerField(help_text='9 целых чисел', unique=True, verbose_name='КПП')),
                ('CEO', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=smart_contract.models.image_folder, verbose_name='Логотип')),
            ],
        ),
    ]
