# Generated by Django 2.2.5 on 2019-10-04 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_contract', '0034_auto_20191002_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='adition_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='verifier',
            field=models.ManyToManyField(blank=True, related_name='verifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
