# Generated by Django 2.2.5 on 2019-10-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0035_auto_20191004_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_for_rating',
            field=models.TextField(blank=True, verbose_name='Пояснение к общей оценке'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_for_rating_competence',
            field=models.TextField(blank=True, verbose_name='Пояснение к оценке компетенции'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_for_rating_employee',
            field=models.TextField(blank=True, verbose_name='Пояснение к оценке сотрудника'),
        ),
    ]
