# Generated by Django 2.2.5 on 2019-10-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0037_auto_20191006_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='competence',
            field=models.ManyToManyField(blank=True, to='smart_contract.Competence', verbose_name='Компетенции компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, verbose_name='О компании'),
        ),
    ]
