# Generated by Django 2.2.5 on 2019-10-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0038_auto_20191006_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccept',
            name='company',
            field=models.CharField(default='АО Карапулечка', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccept',
            name='position',
            field=models.CharField(default='employee', max_length=100),
        ),
    ]
