# Generated by Django 2.2.6 on 2019-10-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0039_auto_20191007_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccept',
            name='company',
        ),
    ]
