# Generated by Django 2.2.6 on 2019-10-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0040_remove_useraccept_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccept',
            old_name='company_test',
            new_name='company',
        ),
    ]
