# Generated by Django 2.2.6 on 2019-10-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0041_auto_20191012_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccept',
            name='role',
            field=models.CharField(choices=[('INVESTOR', 'Инвестор'), ('BUSINESSMAN', 'Предприниматель')], default='INVESTOR', max_length=20),
        ),
    ]
