# Generated by Django 2.2.6 on 2019-10-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0042_useraccept_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccept',
            name='role',
            field=models.CharField(choices=[('INVESTOR', 'Инвестор'), ('BUSINESSMAN', 'Предприниматель')], default='INVESTOR', max_length=20, verbose_name='Роль'),
        ),
    ]
