# Generated by Django 2.2.6 on 2019-11-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0043_auto_20191012_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='prod_doc', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='useraccept',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='prod_doc', verbose_name='Юзерпик'),
        ),
    ]
